FROM node:22-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache openssl
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

EXPOSE 3000

# Start dev server with Nest CLI
CMD ["npm", "run", "start:dev"]
