export const moduleSeeds = [
  {
    moduleName: 'User Management',
    moduleKey: 'users',
    featured: 1,
    sequence: 1,
    menuTitle: 'Users',
    permissions: ['VIEW_USERS', 'CREATE_USERS', 'EDIT_USERS', 'DELETE_USERS'],
  },
  {
    moduleName: 'Role & Permissions',
    moduleKey: 'roles',
    featured: 1,
    sequence: 2,
    menuTitle: 'Roles',
    permissions: ['VIEW_ROLES', 'MANAGE_ROLES'],
  },
  {
    moduleName: 'Hotel & Suites',
    moduleKey: 'suites',
    featured: 1,
    sequence: 3,
    menuTitle: 'Suites',
    permissions: ['VIEW_SUITES', 'MANAGE_SUITES'],
  },
  {
    moduleName: 'Motorcycle Rental',
    moduleKey: 'bikes',
    featured: 1,
    sequence: 4,
    menuTitle: 'Bikes',
    permissions: ['VIEW_BIKES', 'MANAGE_BIKES'],
  },
  {
    moduleName: 'Bookings & Reservations',
    moduleKey: 'bookings',
    featured: 1,
    sequence: 5,
    menuTitle: 'Bookings',
    permissions: ['VIEW_BOOKINGS', 'CREATE_BOOKINGS', 'MANAGE_BOOKINGS'],
  },
  {
    moduleName: 'Reports & Analytics',
    moduleKey: 'reports',
    featured: 1,
    sequence: 6,
    menuTitle: 'Reports',
    permissions: ['VIEW_REPORTS'],
  },
];
