FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 4300

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4300", "--allowed-hosts", "--poll", "1000"]
